name: Benchmark

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

env:
  UV_FROZEN: 'true'
  UV_NO_PROGRESS: 'true'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install uv
        uses: astral-sh/setup-uv@caf0cab7a618c569241d31dcd442f54681755d39 # v3
        with:
          version: "0.5.*"
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync

      - name: Run benchmark
        run: |
          uv run pytest --benchmark-only --benchmark-json benchmark.json

      - name: Commit benchmark results
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add benchmark.json
          git commit -m "Update benchmark results" || echo "No changes to commit"
          git push
