name: Benchmark

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.*" 
          enable-cache: true
    
      - name: Install dependencies
        run: |
          uv sync 
          git restore .

      - name: Run benchmark
        run: |
          uv run pytest -vv --benchmark-only --benchmark-json benchmark.json

      - name: Commit benchmark results
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add benchmark.json
          git commit -m "Update benchmark results" || echo "No changes to commit"
          git push
