name: Test

# Triggers on pushes to main, dev and tags.
on:
  workflow_dispatch:
  push:
    branches:
    - main
    - develop
    tags:
    - 'v*'
    paths:
      # Only run test and docker publish if some code have changed
      - 'pyproject.toml'
      - 'infrastructure/aws/**'
      - 'titiler/**'
      - '.pre-commit-config.yaml'
      - '.github/workflows/ci.yml'

  # Run tests on pull requests.
  pull_request:
env:
  LATEST_PY_VERSION: '3.10'

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.*" 
          enable-cache: true
    
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          uv sync --all-extras

      - name: run pre-commit
        if: ${{ matrix.python-version == env.LATEST_PY_VERSION }}
        run: |
          uv run pre-commit run --all-files

      - name: Run tests
        run: uv run pytest
