name: Test

# Triggers on pushes to main, dev and tags.
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
    paths:
      # Only run test and docker publish if some code have changed
      - 'pyproject.toml'
      - 'infrastructure/aws/**'
      - 'titiler/**'
      - '.pre-commit-config.yaml'
      - '.github/workflows/ci.yml'

  # Run tests on pull requests.
  pull_request:
env:
  LATEST_PY_VERSION: '3.13'
  UV_FROZEN: 'true'
  UV_NO_PROGRESS: 'true'

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13']

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          version: "0.10.*"
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync --all-extras

      - name: run pre-commit
        if: ${{ matrix.python-version == env.LATEST_PY_VERSION }}
        run: |
          uv run pre-commit run --all-files

      - name: Run tests
        run: uv run pytest
