name: CDK Deploy Dev Workflow 🚀

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - feat/add-dev-deploy

jobs:
  deploy:
    name: Deploy to dev 🚀
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: feat/add-dev-deploy

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.deploy_role_arn }}
          role-session-name: test-deploy
          aws-region: us-west-2

      - name: Run titiler-cmr deployment
        uses: "./.github/actions/cdk-deploy"
        with:
          dir: "./infrastructure/aws"
        env:
          TITILER_CMR_ROLE_ARN: ${{ secrets.titiler_cmr_role_arn }}
          TITILER_CMR_STAGE: dev
          TITILER_CMR_ROOT_PATH: ''
