name: CDK Deploy Dev Workflow 🚀

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - test-deploy

jobs:
  define-environment:
    name: Set ✨ environment ✨
    runs-on: ubuntu-latest
    steps:
      - name: Set the environment based on the branch
        id: define_environment
        run: |
          if [ "${{ github.ref }}" = "refs/heads/test-deploy" ]; then
            echo "env_name=test" >> $GITHUB_OUTPUT
          fi
      - name: Print the environment
        run: echo "The environment is ${{ steps.define_environment.outputs.env_name }}"

    outputs:
      env_name: ${{ steps.define_environment.outputs.env_name }}

  deploy:
    name: Deploy to ${{ needs.define-environment.outputs.env_name }} 🚀
    runs-on: ubuntu-latest
    if: ${{ needs.define-environment.outputs.env_name }}
    needs: [define-environment]
    environment: ${{ needs.define-environment.outputs.env_name }}
    concurrency: ${{ needs.define-environment.outputs.env_name }}  

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: test-deploy

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.deploy_role_arn }}
          role-session-name: test-deploy
          aws-region: us-west-2

      - name: Run titiler-cmr deployment
        uses: "./.github/actions/cdk-deploy"
        with:
          dir: "./infrastructure/aws"
          env_aws_secret_name: ${{ vars.ENV_AWS_SECRET_NAME }}
          script_path: "./.github/workflows/generate_env_file.py"
    