name: Documentation
on:
  push:
    branches:
      - develop
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  deploy-versions:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for mike to work with tags

      - uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.*"
          enable-cache: true
      - name: Sync
        run: |
          uv sync
          git restore uv.lock

      - name: Configure Git
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

      - name: Fetch gh-pages branch
        run: |
          git fetch origin gh-pages --depth=1 || true
      
      - name: Deploy docs
        env:
          EARTHDATA_USERNAME: ${{ secrets.earthdata_username }}  
          EARTHDATA_PASSWORD: ${{ secrets.earthdata_password }}  
        run: |
          echo "machine urs.earthdata.nasa.gov\nlogin ${EARTHDATA_USERNAME}\npassword ${EARTHDATA_PASSWORD}" > ~/.netrc
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # For tags, deploy the tagged version
            VERSION=${GITHUB_REF#refs/tags/v}
            uv run mike deploy --push $VERSION
            
            # If this is the latest version, update the 'latest' alias
            LATEST_TAG=$(git tag --sort=-creatordate | head -n 1)
          if [[ "v$VERSION" == "$LATEST_TAG" ]]; then
            uv run mike alias --push $VERSION latest
          fi
          else
            # For develop branch, deploy to 'dev'
            uv run mike deploy --push --update-aliases dev
            uv run mike set-default --push dev
          fi
